site_name: 逆引きKotlin
site_url: http://kotlin-rev-solution.herokuapp.com/site
repo_url: https://github.com/yyYank/kotlin-rev-solution
site_description: JVM言語、Kotlin(ことりん)の逆引きサイトです。基本的な環境導入、文法から、あんなことがしたいこんなことがしたいというKotlinでやりたいことを網羅的に逆引き出来るサイトを目指しています。
site_author: yy_yank
pages:
- [index.md, Home]
- [kotlin-install.md, '目次', 'Kotlinをインストールする']
- [kotlin-plugin-intellij.md, '目次', 'KotlinプラグインをIntelliJ IDEAに導入する']
- [kotlin-plugin-androidstudio.md, '目次', 'KotlinプラグインをAndroid Studioに入れる']
- [hello-kotlin-android.md, '目次', 'AndroidでHelloWorld']
- [kotlin-plugin-eclipse.md, '目次', 'KotlinをEclipseで動かす']
- [variable.md, '目次', '変数を宣言する']
- [type.md, '目次', '型を宣言する']
- [instance.md, '目次', 'インスタンスを生成する']
- [array.md, '目次', '配列を生成する']
- [function.md, '目次', '関数を宣言する']
- [if-statement.md, '目次', '条件分岐を行う']
- [if-function.md, '目次', 'ifを式として扱う']
- [when.md, '目次', 'switchみたいな条件分岐がしたい']
- [loop.md, '目次', 'ループ処理を行う']
- [collection-for-each.md, '目次', 'リストの要素分ループして操作する']
- [collection-filter.md, '目次', '条件でリストを絞り込む']
- [collection-map.md, '目次', 'リストの要素の名前のみを抽出する']
- [collection-merge.md, '目次', 'リストをマージする']
- [collection-sum.md, '目次', 'リストの値を集計する']
- [collection-drop.md, '目次', 'リストの1部分を切り出す']
- [collection-zip.md, '目次', '２つのリストのペアのリストを作る']
